/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./pages/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Full Finova design system palette (from HTML source)
        "primary":                    "#61f4d8",
        "primary-fixed":              "#61f4d8",
        "primary-fixed-dim":          "#4fe5ca",
        "primary-dim":                "#4fe5ca",
        "primary-container":          "#08c1a6",
        "on-primary":                 "#00594c",
        "on-primary-fixed":           "#00443a",
        "on-primary-fixed-variant":   "#006455",
        "on-primary-container":       "#00332b",
        "inverse-primary":            "#006c5c",

        "secondary":                  "#45fec9",
        "secondary-fixed":            "#45fec9",
        "secondary-fixed-dim":        "#2cefbc",
        "secondary-dim":              "#2cefbc",
        "secondary-container":        "#006c52",
        "on-secondary":               "#005d47",
        "on-secondary-fixed":         "#004937",
        "on-secondary-fixed-variant": "#006850",
        "on-secondary-container":     "#dffff0",

        "tertiary":                   "#dee4ff",
        "tertiary-fixed":             "#cad6ff",
        "tertiary-fixed-dim":         "#bcc8f1",
        "tertiary-dim":               "#bcc8f1",
        "tertiary-container":         "#cad6ff",
        "on-tertiary":                "#475275",
        "on-tertiary-fixed":          "#2b3758",
        "on-tertiary-fixed-variant":  "#485376",
        "on-tertiary-container":      "#3e4a6c",

        "surface":                    "#080c22",
        "surface-dim":                "#080c22",
        "surface-bright":             "#242a4c",
        "surface-container-lowest":   "#000000",
        "surface-container-low":      "#0d112a",
        "surface-container":          "#131832",
        "surface-container-high":     "#181d3b",
        "surface-container-highest":  "#1e2343",
        "surface-variant":            "#1e2343",
        "surface-tint":               "#61f4d8",
        "on-surface":                 "#e2e4ff",
        "on-surface-variant":         "#a6a9c6",
        "inverse-surface":            "#fbf8ff",
        "inverse-on-surface":         "#50536d",

        "background":                 "#080c22",
        "on-background":              "#e2e4ff",

        "outline":                    "#70748f",
        "outline-variant":            "#43465f",

        "error":                      "#ff716c",
        "error-dim":                  "#d7383b",
        "error-container":            "#9f0519",
        "on-error":                   "#490006",
        "on-error-container":         "#ffa8a3",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
        mono:     ["Roboto Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        sm:      "0px",
        md:      "0px",
        lg:      "0px",
        xl:      "0px",
        "2xl":   "0px",
        full:    "9999px",
      },
      keyframes: {
        marquee: {
          "0%":   { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        flicker: {
          "0%":   { opacity: "0.97" },
          "5%":   { opacity: "0.95" },
          "10%":  { opacity: "0.9" },
          "15%":  { opacity: "1" },
          "20%":  { opacity: "0.98" },
          "25%":  { opacity: "0.95" },
          "30%":  { opacity: "1" },
          "100%": { opacity: "1" },
        },
        scanline: {
          "0%":   { top: "-100px" },
          "100%": { top: "100%" },
        },
      },
      animation: {
        marquee:  "marquee 30s linear infinite",
        flicker:  "flicker 0.15s infinite",
        scanline: "scanline 8s linear infinite",
      },
    },
  },
  plugins: [],
};
